sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_b489f37019d6_key -iv $encrypted_b489f37019d6_iv -in multi-k8s-327921-6a4e901a2542.json.enc -out multi-k8s-327921-6a4e901a2542.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
