sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_1f818f550743_key -iv $encrypted_1f818f550743_iv -in gc-sa.json.enc -out gc-sa.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
